# Generated by Django 4.1.7 on 2023-02-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
