# Generated by Django 4.1.7 on 2023-02-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_remove_student_student_id_student_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.course'),
        ),
    ]
