# Generated by Django 4.1.7 on 2023-02-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_remove_task_is_completed_taskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='New', max_length=50)),
                ('answer', models.CharField(default='', max_length=1000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
