# Generated by Django 4.1.7 on 2023-03-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0011_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
