# Generated by Django 4.1.7 on 2023-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0012_course_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
