# Generated by Django 4.1.7 on 2023-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0015_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=50),
        ),
    ]
